import { EDUCATION, PORTFOLIO, TECH_SERVICES } from '../PORTFOLIO';
import type { CacheEntry } from './cache';

/** A seed in one line: everything shared, only the interesting fields vary. */
const seed = (
  entry: Pick<CacheEntry, 'id' | 'phrasings' | 'keywords' | 'format' | 'answer' | 'recap'> &
    Partial<Pick<CacheEntry, 'action'>>,
): CacheEntry => ({ action: null, seeded: true, hits: 0, updatedAt: 0, ...entry });

export const SEED_ENTRIES: CacheEntry[] = [
  seed({
    id: 'who-is-johnny',
    phrasings: ['who is johnny', 'tell me about johnny', 'who is he', 'tell me about him', 'introduce johnny', 'who is duc nguyen'],
    keywords: ['who', 'about', 'introduce', 'background', 'himself'],
    format: 'editorial',
    answer: `Software engineer who owns things end to end.\n- 3 years shipping production systems\n- finance, advertising compliance, NDIS, insurance\n- based in Sydney, currently at iMSX`,
    recap: 'Asked who Johnny is; software engineer, end-to-end, Sydney.',
  }),
  seed({
    id: 'resume',
    phrasings: ['can i see his resume', 'show me his resume', 'open resume', 'resume', 'cv', 'show me his cv', 'download resume', 'can i see his cv'],
    keywords: ['resume', 'cv', 'download'],
    format: 'editorial',
    answer: 'Full resume, one click away.',
    recap: 'Asked for the resume; opened it.',
    action: 'resume',
  }),
  seed({
    id: 'experience',
    phrasings: ['whats his experience', 'what is his experience', 'his experience', 'work history', 'walk me through his work history', 'his career', 'past roles', 'where has he worked'],
    keywords: ['experience', 'history', 'roles', 'career', 'worked', 'jobs'],
    format: 'experience',
    answer: 'Four roles, from rivers to enterprise.',
    recap: 'Asked about experience; showed the timeline.',
  }),
  seed({
    id: 'projects',
    phrasings: ['what has he built', 'show me his projects', 'his projects', 'side projects', 'what did he build'],
    keywords: ['projects', 'built', 'building', 'apps', 'portfolio'],
    format: 'projects',
    answer: 'Four builds, all shipped to real users.',
    recap: 'Asked about projects; showed the project rail.',
  }),
  seed({
    id: 'skills',
    phrasings: ['what tech does he use', 'whats his stack', 'his skills', 'what technologies does he use', 'is he full stack', 'what languages does he know'],
    keywords: ['tech', 'technologies', 'stack', 'skills', 'tools', 'languages', 'use', 'fullstack'],
    format: 'list',
    answer: `His toolbox, most-used first.\n${PORTFOLIO.techs.map((t) => `- ${t}`).join('\n')}`,
    recap: 'Asked about his stack; listed the main technologies.',
  }),
  seed({
    id: 'salary',
    phrasings: ['salary expectations', 'what are his salary expectations', 'what are his rates', 'how much does he cost', 'what does he charge'],
    keywords: ['salary', 'rate', 'rates', 'compensation', 'pay', 'cost', 'charge', 'expectations'],
    format: 'editorial',
    answer: `One for ${PORTFOLIO.preferred_name} himself.\n- I only know what he builds, not what he charges\n- ask him directly — takes a minute`,
    recap: 'Asked about salary; pointed at the contact form.',
    action: 'contact-form',
  }),
  seed({
    id: 'contact',
    phrasings: ['how do i reach him', 'how can i contact him', 'contact johnny', 'get in touch', 'i want to talk to him', 'i want to hire him', 'how do i contact johnny'],
    keywords: ['contact', 'reach', 'email', 'talk', 'hire', 'message', 'touch'],
    format: 'editorial',
    answer: 'Right here — I pass messages along.',
    recap: 'Wanted to reach Johnny; opened the form.',
    action: 'contact-form',
  }),
  seed({
    id: 'current-role',
    phrasings: ['whats he doing now', 'what does he do now', 'his current role', 'where does he work now', 'what is he working on now', 'current job'],
    keywords: ['current', 'role', 'now', 'working', 'job', 'imsx'],
    format: 'editorial',
    answer: `Currently at iMSX, enterprise systems.\n- finance, advertising compliance, NDIS, insurance\n- owns features end to end, from build to deploy`,
    recap: 'Asked about his current role; iMSX, enterprise systems, end to end.',
  }),
  seed({
    id: 'databases',
    phrasings: ['is he good with databases', 'what databases does he use', 'his database experience', 'does he know sql', 'whats his database experience'],
    keywords: ['database', 'databases', 'sql', 'postgresql', 'mysql', 'mssql'],
    format: 'list',
    answer: 'Comfortable across a few databases.\n- PostgreSQL\n- MySQL\n- MSSQL\n- Firebase\n- MongoDB',
    recap: 'Asked about databases; PostgreSQL, MySQL, MSSQL, Firebase, MongoDB.',
  }),
  seed({
    id: 'cloud',
    phrasings: ['does he know aws', 'his cloud experience', 'what cloud does he use', 'is he good with cloud', 'whats his aws experience'],
    keywords: ['cloud', 'aws', 'infrastructure', 'devops'],
    format: 'list',
    answer: `Mostly AWS, a lot of mileage.\n${TECH_SERVICES.AWS.slice(0, 8).map((s) => `- ${s}`).join('\n')}`,
    recap: 'Asked about cloud experience; mostly AWS services.',
  }),
  seed({
    id: 'education',
    phrasings: ['what did he study', 'his education', 'where did he study', 'his degree', 'did he go to university', 'whats his degree'],
    keywords: ['education', 'degree', 'university', 'study', 'studied', 'uts'],
    format: 'editorial',
    answer: `One degree, finished with honours.\n- ${EDUCATION.degree}, ${EDUCATION.institution}\n- completed ${EDUCATION.completed}, ${EDUCATION.honours}`,
    recap: 'Asked about education; Bachelor of CS (Honours), UTS, First Class Honours.',
  }),
  seed({
    id: 'location',
    phrasings: ['where is he based', 'where is he located', 'his location', 'where does he live', 'is he in sydney'],
    keywords: ['location', 'based', 'sydney', 'live', 'nsw'],
    format: 'editorial',
    answer: 'Based in Sydney, NSW.\n- Australian Eastern time zone',
    recap: 'Asked where he is based; Sydney, NSW, AEST.',
  }),
  seed({
    id: 'availability',
    phrasings: ['is he available', 'when can he start', 'his availability', 'is he looking for work', 'when is he free'],
    keywords: ['availability', 'available', 'start', 'looking', 'free'],
    format: 'editorial',
    answer: `Best asked directly.\n- I don't track his calendar\n- ask him — takes a minute`,
    recap: 'Asked about availability; pointed at the contact form.',
    action: 'contact-form',
  }),
  seed({
    id: 'work-rights',
    phrasings: ['does he have work rights', 'his work rights', 'is he a citizen', 'can he work in australia', 'does he need sponsorship'],
    keywords: ['work', 'rights', 'visa', 'sponsorship', 'citizen', 'australia'],
    format: 'editorial',
    answer: `One for him to confirm.\n- I don't hold that kind of detail\n- ask him directly — takes a minute`,
    recap: 'Asked about work rights; pointed at the contact form.',
    action: 'contact-form',
  }),
  seed({
    id: 'remote',
    phrasings: ['does he work remote', 'is he open to remote work', 'can he work remotely', 'is he open to relocating', 'does he do remote work'],
    keywords: ['remote', 'relocate', 'relocating', 'onsite', 'hybrid'],
    format: 'editorial',
    answer: `Best asked directly.\n- arrangements vary role to role\n- ask him — takes a minute`,
    recap: 'Asked about remote work; pointed at the contact form.',
    action: 'contact-form',
  }),
  seed({
    id: 'strengths',
    phrasings: ['whats he good at', 'his strengths', 'what are his strengths', 'whats he best at', 'what is he good at'],
    keywords: ['strengths', 'good', 'best', 'strong'],
    format: 'rail',
    answer: `A few things he leans on.\n- Ownership | takes a feature from analysis through deploy\n- Range | comfortable across frontend, backend and infra\n- Steadiness | ships under tight sprints without cutting corners`,
    recap: 'Asked about his strengths; ownership, range, steadiness.',
  }),
  seed({
    id: 'why-hire',
    phrasings: ['why should we hire him', 'why hire him', 'what makes him a good hire', 'should we hire him', 'why pick him'],
    keywords: ['hire', 'why', 'pick'],
    format: 'editorial',
    answer: `Not my call to make.\n- he owns features end to end\n- shipped under tight sprints for a few years`,
    recap: 'Asked why hire him; pointed to ownership and experience.',
  }),
  seed({
    id: 'github',
    phrasings: ['does he have a github', 'his github', 'wheres his github', 'can i see his code', 'his github profile'],
    keywords: ['github', 'code', 'repos', 'repositories'],
    format: 'editorial',
    answer: `His GitHub is linked on the page.\n- profile icons up top go straight there`,
    recap: 'Asked about his GitHub; pointed at the profile link.',
  }),
  seed({
    id: 'fun-fact',
    phrasings: ['tell me a fun fact', 'fun fact about him', 'something interesting about him', 'give me a fun fact', 'whats a fun fact'],
    keywords: ['fun', 'fact', 'interesting', 'random'],
    format: 'editorial',
    answer: `He's rebuilt this site more than he'd admit.\n- a few too many redesigns to count`,
    recap: 'Asked for a fun fact; he keeps redesigning this site.',
  }),
  seed({
    id: 'ai-tools',
    phrasings: ['does he use ai tools', 'does he use claude', 'his ai workflow', 'does he use ai', 'how does he use ai'],
    keywords: ['ai', 'tools', 'claude', 'workflow'],
    format: 'editorial',
    answer: `Claude Code is part of his day.\n- uses it for real production work, not demos`,
    recap: 'Asked about AI tools; Claude Code is part of his workflow.',
  }),
];
