// Generated by `npm run resume` from public/resume.pdf. Do not edit.

export interface ResumePage {
  src: string;
  width: number;
  height: number;
}

export const RESUME_PAGES: ResumePage[] = [
  {
    "src": "/resume/page-1.png",
    "width": 1656,
    "height": 2339
  }
];
