/**
 * Rasterizes public/resume.pdf into page images and writes the manifest the
 * viewer reads.
 *
 *   npm run resume
 *
 * This is a local step, not part of `next build` — Vercel's build container has
 * no poppler — so its output is committed alongside the PDF.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

/** A4 at 200dpi is 1654×2339 — enough for next/image to downscale crisply. */
const DPI = 200;

const ROOT = process.cwd();
const PDF = path.join(ROOT, 'public/resume.pdf');
const OUT_DIR = path.join(ROOT, 'public/resume');
const MANIFEST = path.join(ROOT, 'src/app/_resume/pages.ts');

/** PNG dimensions sit at a fixed offset inside the IHDR chunk, so reading the
 *  first 24 bytes avoids taking on an image library for two numbers. */
function pngSize(file: string): { width: number; height: number } {
  const header = Buffer.alloc(24);
  const fd = fs.openSync(file, 'r');
  fs.readSync(fd, header, 0, 24, 0);
  fs.closeSync(fd);
  return { width: header.readUInt32BE(16), height: header.readUInt32BE(20) };
}

/** pdftoppm zero-pads its output once a document passes nine pages, so sort on
 *  the parsed number rather than the filename. */
function pageNumber(name: string): number {
  const match = name.match(/-(\d+)\.png$/);
  return match ? Number(match[1]) : 0;
}

if (!fs.existsSync(PDF)) {
  console.error('public/resume.pdf is missing. Export the resume and drop it in.');
  process.exit(1);
}

try {
  execFileSync('pdftoppm', ['-v'], { stdio: 'ignore' });
} catch {
  console.error('pdftoppm not found. Install poppler:  brew install poppler');
  process.exit(1);
}

// Render into a scratch directory first so a failed run cannot leave a
// half-written public/resume behind.
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'resume-'));
execFileSync('pdftoppm', ['-png', '-r', String(DPI), PDF, path.join(scratch, 'page')]);

const rendered = fs
  .readdirSync(scratch)
  .filter((name) => name.endsWith('.png'))
  .sort((a, b) => pageNumber(a) - pageNumber(b));

if (rendered.length === 0) {
  fs.rmSync(scratch, { recursive: true, force: true });
  console.error('pdftoppm produced no pages.');
  process.exit(1);
}

fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

const pages = rendered.map((name, index) => {
  const file = `page-${index + 1}.png`;
  const target = path.join(OUT_DIR, file);
  fs.copyFileSync(path.join(scratch, name), target);
  return { src: `/resume/${file}`, ...pngSize(target) };
});

fs.rmSync(scratch, { recursive: true, force: true });

fs.mkdirSync(path.dirname(MANIFEST), { recursive: true });
fs.writeFileSync(
  MANIFEST,
  [
    '// Generated by `npm run resume` from public/resume.pdf. Do not edit.',
    '',
    'export interface ResumePage {',
    '  src: string;',
    '  width: number;',
    '  height: number;',
    '}',
    '',
    `export const RESUME_PAGES: ResumePage[] = ${JSON.stringify(pages, null, 2)};`,
    '',
  ].join('\n'),
);

console.log(`build-resume: ${pages.length} page(s) at ${DPI}dpi → public/resume/`);
